config_Kakeibo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kakeibo.urls')),
]

kakeibo/urls.py
from django.urls import path
from . import views

app_name = 'kakeibo'

urlpatterns = [
    path('', views.PaymentList.as_view(), name='payment_list'),
    path('income_list/', views.IncomeList.as_view(), name='income_list'),
    path('payment_create/', views.PaymentCreate.as_view(), name='payment_create'),
    path('income_create/', views.IncomeCreate.as_view(), name='income_create'),
    path('payment_update/<int:pk>/', views.PaymentUpdate.as_view(), name='payment_update'),
    path('income_update/<int:pk>/', views.IncomeUpdate.as_view(), name='income_update'),
    path('payment_delete/<int:pk>/', views.PaymentDelete.as_view(), name='payment_delete'),
    path('income_delete/<int:pk>/', views.IncomeDelete.as_view(), name='income_delete'),
    path('month_dashboard/<int:year>/<int:month>/', views.MonthDashboard.as_view(), name='month_dashboard'),
]

kakeibo/models.py
from django.db import models

# Create your models here.
from django.db import models


class PaymentCategory(models.Model):
    name = models.CharField('カテゴリ名', max_length=32)

    def __str__(self):
        return self.name


class Payment(models.Model):
    date = models.DateField('日付')
    price = models.IntegerField('金額')
    category = models.ForeignKey(PaymentCategory, on_delete=models.PROTECT, verbose_name='カテゴリ')
    description = models.TextField('摘要', null=True, blank=True)


class IncomeCategory(models.Model):
    name = models.CharField('カテゴリ名', max_length=32)

    def __str__(self):
        return self.name


class Income(models.Model):
    date = models.DateField('日付')
    price = models.IntegerField('金額')
    category = models.ForeignKey(IncomeCategory, on_delete=models.PROTECT, verbose_name='カテゴリ')
    description = models.TextField('摘要', null=True, blank=True)

register/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

kakeibo/forms.py
from django import forms
from .models import PaymentCategory, Payment, Income 
from django.utils import timezone
from .widgets import CustomRadioSelect


'''
    支出検索フォーム
'''
class PaymentSearchForm(forms.Form):
    # 年の選択肢を動的に作る
    start_year = 2019  # 家計簿の登録を始めた年
    end_year = timezone.now().year + 1  # 現在の年＋１年
    years = [(year, f'{year}年') for year in reversed(range(start_year, end_year + 1))]
    years.insert(0, (0, ''))  # 空白の選択を追加
    YEAR_CHOICES = tuple(years)
    # 月の選択肢を動的に作る
    months = [(month, f'{month}月') for month in range(1, 13)]
    months.insert(0, (0, ''))
    MONTH_CHOICES = tuple(months)

    # 年の選択
    year = forms.ChoiceField(
        label='年での絞り込み',
        required=False,
        choices=YEAR_CHOICES,
        widget=forms.Select(attrs={'class': 'form'})
    )
    # 月の選択
    month = forms.ChoiceField(
        label='月での絞り込み',
        required=False,
        choices=MONTH_CHOICES,
        widget=forms.Select(attrs={'class': 'form'})
    )
    # 〇〇円以上
    greater_than = forms.IntegerField(
        label='Greater Than',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form',
                                      'autocomplete': 'off',
                                      'placeholder': '〇〇円以上'})
    )
    # 〇〇円以下
    less_than = forms.IntegerField(
        label='Less Than',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form',
                                      'autocomplete': 'off',
                                      'placeholder': '〇〇円以下'})
    )
    # キーワード
    key_word = forms.CharField(
        label='検索キーワード',
        required=False,
        widget=forms.TextInput(attrs={'class': 'form',
                                      'autocomplete': 'off',
                                      'placeholder': 'キーワード',
                                      })
    )
    # カテゴリー検索
    category = forms.ModelChoiceField(
        label='カテゴリでの絞り込み',
        required=False,
        queryset=PaymentCategory.objects.order_by('name'),
        widget=forms.Select(attrs={'class': 'form'})
    )

'''
    
'''
class IncomeSearchForm(forms.Form):
    start_year = 2019
    end_year = timezone.now().year + 1
    years = [(year, f'{year}年') for year in reversed(range(start_year, end_year + 1))]
    years.insert(0, (0, ''))
    YEAR_CHOICES = tuple(years)

    months = [(month, f'{month}月') for month in range(1, 13)]
    months.insert(0, (0, ''))
    MONTH_CHOICES = tuple(months)

    year = forms.ChoiceField(
        label='年での絞り込み',
        required=False,
        choices=YEAR_CHOICES,
        widget=forms.Select(attrs={'class': 'form', 'value': ''})
    )

    month = forms.ChoiceField(
        label='月での絞り込み',
        required=False,
        choices=MONTH_CHOICES,
        widget=forms.Select(attrs={'class': 'form'})
    )

'''
    支出登録フォーム
'''
class PaymentCreateForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form'
            field.widget.attrs['placeholder'] = field.label
            field.widget.attrs['autocomplete'] = 'off'

'''
    収入登録フォーム
'''
class IncomeCreateForm(forms.ModelForm):
    class Meta:
        model = Income
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form'
            field.widget.attrs['placeholder'] = field.label
            field.widget.attrs['autocomplete'] = 'off'

kakeibo/views.py
from django.views import generic
from .models import Payment, PaymentCategory, Income, IncomeCategory
from .forms import PaymentSearchForm, IncomeSearchForm, PaymentCreateForm, IncomeCreateForm  # 追加
from django.urls import reverse_lazy  # 追加
from django.contrib import messages  # 追加
from django.shortcuts import redirect  # 追加
import numpy as np
import pandas as pd
from django_pandas.io import read_frame
from .plugin_plotly import GraphGenerator


'''
    
'''
class PaymentList(generic.ListView):
    template_name = 'kakeibo/payment_list.html'
    model = Payment
    ordering = '-date'
    paginate_by = 10

    # 追加
    def get_queryset(self):
        queryset = super().get_queryset()
        self.form = form = PaymentSearchForm(self.request.GET or None)

        if form.is_valid():
            year = form.cleaned_data.get('year')
            # 何も選択されていないときは0の文字列が入るため、除外
            if year and year != '0':
                queryset = queryset.filter(date__year=year)

            # 何も選択されていないときは0の文字列が入るため、除外
            month = form.cleaned_data.get('month')
            if month and month != '0':
                queryset = queryset.filter(date__month=month)

            # 〇〇円以上の絞り込み
            greater_than = form.cleaned_data.get('greater_than')
            if greater_than:
                queryset = queryset.filter(price__gte=greater_than)
            
            # 〇〇円以下の絞り込み
            less_than = form.cleaned_data.get('less_than')
            if less_than:
                queryset = queryset.filter(price__lte=less_than)
            
            # キーワードの絞り込み
            key_word = form.cleaned_data.get('key_word')
            if key_word:
                # 空欄で区切り、順番に絞る、and検索
                if key_word:
                    for word in key_word.split():
                        queryset = queryset.filter(description__icontains=word)
            
            # カテゴリでの絞り込み
            category = form.cleaned_data.get('category')
            if category:
                queryset = queryset.filter(category=category)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # search formを渡す
        context['search_form'] = self.form

        return context


'''
    収入一覧
'''
class IncomeList(generic.ListView):
    template_name = 'kakeibo/income_list.html'
    model = Income
    ordering = '-date'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.form = form = IncomeSearchForm(self.request.GET or None)

        if form.is_valid():
            year = form.cleaned_data.get('year')
            if year and year != '0':
                queryset = queryset.filter(date__year=year)

            month = form.cleaned_data.get('month')
            if month and month != '0':
                queryset = queryset.filter(date__month=month)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['search_form'] = self.form

        return context


'''
    支出登録
'''
class PaymentCreate(generic.CreateView):
    template_name = 'kakeibo/register.html'
    model = Payment
    form_class = PaymentCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '支出登録'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:payment_list')

    # 追加
    # バリデーション時にメッセージを保存
    def form_valid(self, form):
        self.object = payment = form.save()
        messages.info(self.request,
                      f'支出を登録しました\n'
                      f'日付:{payment.date}\n'
                      f'カテゴリ:{payment.category}\n'
                      f'金額:{payment.price}円')
        return redirect(self.get_success_url())


'''
    収入登録
'''
class IncomeCreate(generic.CreateView):
    template_name = 'kakeibo/register.html'
    model = Income
    form_class = IncomeCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '収入登録'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:income_list')

    def form_valid(self, form):
        self.object = income = form.save()
        messages.info(self.request,
                      f'収入を登録しました\n'
                      f'日付:{income.date}\n'
                      f'カテゴリ:{income.category}\n'
                      f'金額:{income.price}円')
        return redirect(self.get_success_url())


'''
    支出更新
'''
class PaymentUpdate(generic.UpdateView):
    template_name = 'kakeibo/register.html'
    model = Payment
    form_class = PaymentCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '支出更新'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:payment_list')

    def form_valid(self, form):
        self.object = payment = form.save()
        messages.info(self.request,
                      f'支出を更新しました\n'
                      f'日付:{payment.date}\n'
                      f'カテゴリ:{payment.category}\n'
                      f'金額:{payment.price}円')
        return redirect(self.get_success_url())


'''
    収入更新
'''
class IncomeUpdate(generic.UpdateView):
    template_name = 'kakeibo/register.html'
    model = Income
    form_class = IncomeCreateForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '収入更新'
        return context

    def get_success_url(self):
        return reverse_lazy('kakeibo:income_list')

    def form_valid(self, form):
        self.object = income = form.save()
        messages.info(self.request,
                      f'収入を更新しました\n'
                      f'日付:{income.date}\n'
                      f'カテゴリ:{income.category}\n'
                      f'金額:{income.price}円')
        return redirect(self.get_success_url())


'''
    支出削除
'''
class PaymentDelete(generic.DeleteView):
    template_name = 'kakeibo/delete.html'
    model = Payment

    def get_success_url(self):
        return reverse_lazy('kakeibo:payment_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '支出削除確認'

        return context

    def delete(self, request, *args, **kwargs):
        self.object = payment = self.get_object()

        payment.delete()
        messages.info(self.request,
                      f'支出を削除しました\n'
                      f'日付:{payment.date}\n'
                      f'カテゴリ:{payment.category}\n'
                      f'金額:{payment.price}円')
        return redirect(self.get_success_url())


'''
    収入削除
'''
class IncomeDelete(generic.DeleteView):
    template_name = 'kakeibo/delete.html'
    model = Income

    def get_success_url(self):
        return reverse_lazy('kakeibo:income_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = '収入削除確認'

        return context

    def delete(self, request, *args, **kwargs):
        self.object = income = self.get_object()
        income.delete()
        messages.info(self.request,
                      f'収入を削除しました\n'
                      f'日付:{income.date}\n'
                      f'カテゴリ:{income.category}\n'
                      f'金額:{income.price}円')
        return redirect(self.get_success_url())


'''
    
'''
class MonthDashboard(generic.TemplateView):
    """月間支出ダッシュボード"""
    template_name = 'kakeibo/month_dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # これから表示する年月
        year = int(self.kwargs.get('year'))
        month = int(self.kwargs.get('month'))
        context['year_month'] = f'{year}年{month}月'

        # 前月と次月をコンテキストに入れて渡す
        if month == 1:
            prev_year = year - 1
            prev_month = 12
        else:
            prev_year = year
            prev_month = month - 1

        if month == 12:
            next_year = year + 1
            next_month = 1
        else:
            next_year = year
            next_month = month + 1
        context['prev_year'] = prev_year
        context['prev_month'] = prev_month
        context['next_year'] = next_year
        context['next_month'] = next_month
        # ここから追加
        # paymentモデルをdfにする
        queryset = Payment.objects.filter(date__year=year)
        queryset = queryset.filter(date__month=month)
        # クエリセットが何もない時はcontextを返す
        # 後の工程でエラーになるため
        if not queryset:
            return context

        df = read_frame(queryset,
                        fieldnames=['date', 'price', 'category'])

        # グラフ作成クラスをインスタンス化
        gen = GraphGenerator()

        # pieチャートの素材を作成
        df_pie = pd.pivot_table(df, index='category', values='price', aggfunc=np.sum)
        pie_labels = list(df_pie.index.values)
        pie_values = [val[0] for val in df_pie.values]
        plot_pie = gen.month_pie(labels=pie_labels, values=pie_values)
        context['plot_pie'] = plot_pie

        # テーブルでのカテゴリと金額の表示用。
        # {カテゴリ:金額,カテゴリ:金額…}の辞書を作る
        context['table_set'] = df_pie.to_dict()['price']

        # totalの数字を計算して渡す
        context['total_payment'] = df['price'].sum()

        # 日別の棒グラフの素材を渡す
        df_bar = pd.pivot_table(df, index='date', values='price', aggfunc=np.sum)
        dates = list(df_bar.index.values)
        heights = [val[0] for val in df_bar.values]
        plot_bar = gen.month_daily_bar(x_list=dates, y_list=heights)
        context['plot_bar'] = plot_bar

        return context

register/views.py
from django.shortcuts import render

# Create your views here.

kakeibo/templates/kakeibo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>家計簿アプリ</title>
  <link rel="stylesheet" href="{% static 'kakeibo/css/reset.css' %}">
  <link rel="stylesheet" href="{% static 'kakeibo/css/style.css' %}">
  {% block extrajs %}{% endblock %}
</head>

<body>
  <header class="page-header">
    <h1>
      <a href="{% url 'kakeibo:payment_list' %}" class="header-title">家計簿アプリ</a>
    </h1>
    <nav class="nav">
      <ul class="main-nav ml-5">
        <li class="ml-5">
          <a href="{% url 'kakeibo:payment_list'%}">支出一覧</a>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:income_list'%}">収入一覧</a>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:payment_create'%}">支出登録</a>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:income_create'%}">収入登録</a>
        </li>
        <li class="ml-5">
          <a href="{% url 'kakeibo:month_dashboard' now_year now_month%}">月間支出</a>
        </li>
    </nav>
  </header>

  <div class="layout">
    <div class="container">
      <main>
        <!-- メッセージがある場合は表示する -->
        {% if messages %}
        <div class="alert alert-success js-alert" id="js-alert">
          <button class="alert-btn-close js-alert-close" type="button">ｘ</button>
          <!-- メッセージを取り出す -->
          {% for message in messages %}
          <p> {{ message|linebreaks }}</p>
          {% endfor %}
        </div>
        {% endif %}
        {% block content %}{% endblock %}
      </main>
    </div>
  </div>

  <script type="text/javascript">
    // ×を押して閉じられるようにする
    for (const element of document.querySelectorAll('.js-alert > .js-alert-close')) {
      element.addEventListener('click', e => {
        e.target.parentElement.classList.add('is-hidden');
      });
    }
  </script>

</body>

</html>

kakeibo/templates/kakeibo/delete.html
{% extends 'kakeibo/base.html' %}

{% block content %}
<h1>{{ page_title }}</h1>
<p class="mt-5"> 本当に削除してよろしいですか？</p>

<p class="mt-4">日付：{{ object.date }}</p>
<p class="mt-4">カテゴリ：{{ object.category }}</p>
<p class="mt-4">金額：{{ object.price }}</p>
<p class="mt-4">摘要： {% if object.description %}{{ object.description }}{% endif %}</p>

<form class="mt-4" method="post">
  {% csrf_token %}
  <!-- ページタイトルから戻ろ一覧を分岐 -->
  {% if '支出' in page_title %}
  <a class="btn btn-info" href="{% url 'kakeibo:payment_list'%}">
    いいえ、一覧に戻ります
  </a>
  {% else %}
  <a class="btn btn-info" href="{% url 'kakeibo:income_list'%}">
    いいえ、一覧に戻ります
  </a>
  {% endif %}
  <button type="submit" class="btn btn-danger">
    はい、削除します
  </button>
</form>

{% endblock %}

kakeibo/templates/kakeibo/income_list.html
{% extends 'kakeibo/base.html' %}
{% load humanize %}
{% load kakeibo %}
{% block content %}

<form class="mt-2" id="search-form" action="" method="GET">
  <label class="label mr-4">年月</label>
  {{ search_form.year }}
  {{ search_form.month }}
  <button class="btn btn-info ml-4" type="submit">検索</button>
</form>

<p class="search-result mt-3"> {{ page_obj.paginator.count }}件の検索結果 </p>

<table class="table mt-3">
  <tr>
    <th>日付</th>
    <th>カテゴリ</th>
    <th>金額</th>
    <th>摘要</th>
    <th>編集</th>
  </tr>
  {% for income in income_list %}

  <tr>
    <td>{{ income.date }}</td>
    <td>{{ income.category }}</td>
    <td>{{ income.price|intcomma}}</td>
    <td>
      {% if income.description %}
      {{ income.description }}
      {% endif %}
    </td>
    <td>
        <div class="manage-btn-area">
          <div class="update-btn-area">
            <a class="btn btn-info" href="{% url 'kakeibo:income_update' income.pk %}">更新</a>
          </div>
          <div class="delete-btn-area">
            <a class="btn btn-danger" href="{% url 'kakeibo:income_delete' income.pk %}">削除</a>
          </div>
        </div>
      </td>
  </tr>
  {% endfor %}
</table>

<div class="mt-5">
  {% if page_obj.has_previous %}
  <a class="mr-2 font-weight-bold" href="?{% url_replace request 'page' page_obj.previous_page_number %}" title="前ページへ">前へ</a>
  {% endif %}

  <span style="color:#0d1a3c">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>

  {% if page_obj.has_next %}
  <a class="ml-2 font-weight-bold" href="?{% url_replace request 'page' page_obj.next_page_number %}" title="次ページへ">次へ</a>
  {% endif %}
</div>

{% endblock %}

kakeibo/templates/kakeibo/month_dashboard.html
{% extends 'kakeibo/base.html' %}
{% load humanize %}
{% block content %}

<div class="month-pager">
  <a href="{% url 'kakeibo:month_dashboard' prev_year prev_month %}">
    前月
  </a>
  <span class="ml-4 mr-4">{{ year_month }}</span>
  <a href="{% url 'kakeibo:month_dashboard' next_year next_month %}">
    次月
  </a>
</div>
{% autoescape off %}
<div class="month-dash-page-top mt-4">
  <div class="left card">
    <table class="table">
      <tr>
        <th>カテゴリ</th>
        <th>金額</th>
      </tr>
      {% for key,value in table_set.items %}
      <tr>
        <td>{{ key }}</td>
        <td>{{ value|intcomma }}</td>
      </tr>
      {% endfor %}
      <tr>
        <td>Total</td>
        <td>{{ total_payment|intcomma }}</td>
      </tr>
    </table>
  </div>
  <div class="right ml-4 hidden_toolbar">
    {{ plot_pie }}
  </div>
</div>
<div class="month-dash-bottom">
  <div class="hidden_toolbar">
    {{ plot_bar }}
  </div>
</div>
{% endautoescape %}

{% endblock %}
{% block extrajs %}
<!-- plotlyのjs -->
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
{% endblock%}

kakeibo/templates/kakeibo/payment_list.html
{% extends 'kakeibo/base.html' %}
{% load humanize %}
{% load kakeibo %}

{% block content %}
<!-- 検索フォーム -->
<form class="mt-2" id="search-form" action="" method="GET">
  <div>
    <label class="label mr-4">年月</label>
    {{ search_form.year }}
    {{ search_form.month }}
  </div>
  <div class="mt-4">
    <label class="label mr-4">金額</label>
    {{ search_form.greater_than }}
    <span class="ml-4 mr-4">～</span>
    {{ search_form.less_than }}
  </div>
  <div class="mt-4">
    {{ search_form.key_word }}
    <button class="btn btn-info ml-4" type="submit">検索</button>
  </div>
  <div class="mt-2 inline">
    {{ search_form.category }}
  </div>
</form>

<!-- 表示件数 -->
<p class="search-result mt-3"> {{ page_obj.paginator.count }}件の検索結果 </p>

<!-- 一覧表示 -->
<table class="table mt-3">
  <tr>
    <th>日付</th>
    <th>カテゴリ</th>
    <th>金額</th>
    <th>摘要</th>
    <th>編集</th> 
  </tr>
  {% for payment in payment_list %}

  <tr>
    <td>{{ payment.date }}</td>
    <td>{{ payment.category }}</td>
    <td>{{ payment.price|intcomma}}</td>
    <td>
      {% if payment.description %}
      {{ payment.description }}
      {% endif %}
    </td>
    <td>
      <div class="manage-btn-area">
        <div class="update-btn-area">
          <a class="btn btn-info" href="{% url 'kakeibo:payment_update' payment.pk %}">更新</a>
        </div>
        <div class="delete-btn-area">
          <a class="btn btn-danger" href="{% url 'kakeibo:payment_delete' payment.pk %}">削除</a>
        </div>
      </div>
    </td>
  </tr>
  {% endfor %}
</table>

<!-- ページネーション -->
<div class="mt-5">
  <!-- 1つ前 -->
  {% if page_obj.has_previous %}
  <a class="mr-2 prev" href="?{% url_replace request 'page' page_obj.previous_page_number %}" title="前ページへ">前へ</a>
  {% endif %}

  <!-- nページ目/トータルページ数 -->
  <span style="color:#0d1a3c">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>

  <!-- 1つ後 -->
  {% if page_obj.has_next %}
  <a class="ml-2 next" href="?{% url_replace request 'page' page_obj.next_page_number %}" title="次ページへ">次へ</a>
  {% endif %}
</div>

{% endblock %}


{% block extrajs %}
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', e => {
    const searchForm = document.getElementById('search-form');

    //カテゴリがクリックされたら検索実行
    for (const check of document.getElementsByName('category')) {
      check.addEventListener('change', () => {
        searchForm.submit();
      });
    }

    // 選択済みのカテゴリがクリックされたらチェックを解除して検索実行
    const selectedCategory = document.querySelector(`input[name='category']:checked`)
    if (selectedCategory) {
      selectedCategory.onclick = () => {
        selectedCategory.checked = false
        searchForm.submit();
      }
    }
  });
</script>
{% endblock %}

kakeibo/templates/kakeibo/register.html
{% extends 'kakeibo/base.html' %}

{% block content %}
<h1>{{ page_title }}</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="mt-4">
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  <button class="btn mt-4" type="submit" name="button">送信</button>
</form>

<!-- date picker -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script type="text/javascript">
  $(function() {
    $('#id_date').datepicker({
      dateFormat: 'yy-mm-dd',
      firstDay: 1,
      dayNamesMin: ["日", "月", "火", "水", "木", "金", "土"],
      monthNames: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    });
  })
</script>
{% endblock %}